name: skeleton
description: A new Flutter project.
publish_to: 'none'
version: 1.1.5+8

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.6
  flutter_easyloading: ^3.0.5
  flutter_screenutil: ^5.9.0

  # State management
  flutter_riverpod: ^2.4.0
  riverpod_annotation: ^2.1.5
  stack_trace: 1.11.0 #downgrade due to flutter_test

  # API
  pretty_dio_logger: ^1.3.1
  dio_smart_retry: ^5.0.0
  dio: ^5.3.2

  # Package information / Update
  package_info_plus: ^4.1.0

  # Firebase
  # firebase_core: ^2.15.1
  # firebase_crashlytics: ^3.3.5
  # firebase_messaging: ^14.6.7

  # Local storage
  flutter_secure_storage: ^9.0.0

  # DateFormat / Translations
  intl: ^0.18.1

  # Navigation
  go_router: ^10.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.3
  build_runner: ^2.4.6
  riverpod_generator: ^2.3.2
  riverpod_lint: ^2.0.4
  custom_lint: ^0.5.3

flutter:
  uses-material-design: true

  assets:
    - assets/translations/